com:
  setupAwsAccessKey: AWS アクセスキーの設定
  accessKeyId: アクセスキーID
  secretAccessKey: シークレットアクセスキー
  setPassword: 起動パスワード設定
  setPasswordMsg: アプリ起動時のパスワードを設定します。次回起動時にはパスワード入力が必要です。
  inputPassword: パスワード入力
  updatePassword: パスワード変更
  currentPassword: 現在のパスワード
  newPassword: 新しいパスワード
  newPassword2: 新しいパスワード（再入力）
  password: パスワード
  action: 操作
  cancel: キャンセル
  save: 保存する
  ok: OK
  set: 設定する
  create: 作成する
  delete: 削除する
  error:
    invalidPassword: パスワードが正しくありません。
    passwordsDoNotMatch: パスワードが一致しません。
s3:
  serviceName: S3
  buckets: バケット
  name: 名称
  size: サイズ
  lastModified: 最終更新日時
  createBucket: 新規バケット作成
  deleteBucket: バケット削除
  bucketProperties: バケットのプロパティ
  createFolder: フォルダ作成
  downloadObjects: ダウンロード
  uploadObjects: ファイルのアップロード
  deleteObjects: 削除
  deleteConfirmation: 削除の確認
  deleteObjMsg1: "%s を削除しますか？"
  deleteObjMsg2: "%d 個のオブジェクトを削除しますか？"
  deleteBktMsg: バケット %s を削除しますか？
  folderName: フォルダ名
  region: リージョン
  noObject: オブジェクトがありません。
  bucketName: バケット名
  create: 作成
  delete: 削除
  startUpload: アップロード開始
  uploadTo: アップロード先
  storageClass: ストレージ クラス
  storageClassName: 
    STANDARD: 標準
    REDUCED_REDUNDANCY: 低冗長化
    STANDARD_IA: 標準 - 低頻度アクセス
  regionName:
    us-east-1: US 東海岸（北バージニア）
    us-west-1: US 西海岸（北カルフォルニア）
    us-west-2: US 西海岸（オレゴン）
    eu-west-1: EU （アイルランド）
    eu-central-1: EU （フランクフルト）
    ap-southeast-1: アジアパシフィック（シンガポール）
    ap-southeast-2: アジアパシフィック（シドニー）
    ap-northeast-1: アジアパシフィック（東京）
    sa-east-1: 南アメリカ（サンパウロ）
  error:
    InvalidAccessKeyId: アクセスキーIDが正しくありません。
    SignatureDoesNotMatch: シークレットアクセスキーが正しくありません。
    BucketAlreadyExists: このバケット名は既に存在します。
    InvalidBucketName: このバケット名は利用できません。
    TooManyBuckets: 許可されているバケット数を超えています。
    BucketNotEmpty: このバケットは空ではありません。
    NoSuchBucket: 指定したバケットは存在しません。
    ServiceUnavailable: サービスが利用できません。
    InternalError: サーバー内部エラー
    AccessDenied: アクセスできません。
ec2:
  serviceName: EC2
  regionName:
    all: 全てのリージョン
    us-east-1: US 東海岸（北バージニア）
    us-west-2: US 西海岸（オレゴン）
    us-west-1: US 西海岸（北カルフォルニア）
    eu-west-1: EU （アイルランド）
    eu-central-1: EU （フランクフルト）
    ap-southeast-1: アジアパシフィック（シンガポール）
    ap-southeast-2: アジアパシフィック（シドニー）
    ap-northeast-1: アジアパシフィック（東京）
    sa-east-1: 南アメリカ（サンパウロ）
  instance: インスタンス
  start: 開始
  stop: 停止
  reboot: 再起動
  terminate: 削除
  startInstances: インスタンスの開始
  stopInstances: インスタンスの停止
  rebootInstances: インスタンスの再起動
  terminateInstances: インスタンスの削除
  noInstances: インスタンスはありません。
  startInstancesMsg:
   - このインスタンスを開始してよろしいですか？
   - これらのインスタンスを開始してよろしいですか？
  rebootInstancesMsg:
   - このインスタンスを再起動してよろしいですか？
   - これらのインスタンスを再起動してよろしいですか？
  stopInstancesMsg:
   - このインスタンスを停止してよろしいですか？
   - これらのインスタンスを停止してよろしいですか？
  stopInstancesMsg2: |+
   インスタンスを停止すると
   インスタンスのエフェメラルストレージ上のデータは失われます。
  terminateInstancesMsg:
   - このインスタンスを削除してよろしいですか？
   - これらのインスタンスを削除してよろしいですか？
  terminateInstancessMsg2: ""
r53:
  serviceName: Route53
  zones: ゾーン
  name: ドメイン名
  ttl: TTL
  type: タイプ
  value: 値
  noHostedZone: ホストされたゾーンはありません。
  createHostedZone: ホストゾーンの作成
  deleteHostedZone: ホストゾーンの削除
  deleteHostedZoneMsg: このホストゾーンを削除してよろしいですか？
  createRRSet: レコードセットの作成
  updateRRSet: レコードセットの変更
  deleteRRSet: レコードセットの削除
  deleteRRSetMsg:
   - このレコードセットを削除してよろしいですか？
   - これらのレコードセットを削除してよろしいですか？
  domainName: ドメイン名
  comment: コメント
  hostedZoneType: タイプ
  notPrivateZone: パブリック
  privateZone: プライベート（VPC用）
  associatedVpc: 連携VPC
  rrsetType: タイプ
  ttlBtn:
    "1min": 1分
    "5min": 5分
    "1hour": 1時間
    "1day": 1日
  error:
    AccessDenied: アクセスできません。
    InvalidDomainName: ドメイン名が正しくありません。
    RRSetAlreadyExists: すでに登録されています。
