com:
  setupAwsAccessKey: AWS アクセスキーの設定
  accessKeyId: アクセスキーID
  secretAccessKey: シークレットアクセスキー
  setPassword: 起動パスワード設定
  setPasswordMsg: アプリ起動時のパスワードを設定します。次回起動時にはパスワード入力が必要です。
  inputPassword: パスワード入力
  updatePassword: パスワード変更
  currentPassword: 現在のパスワード
  newPassword: 新しいパスワード
  newPassword2: 新しいパスワード（再入力）
  password: パスワード
  action: 操作
  cancel: キャンセル
  save: 保存する
  ok: OK
  set: 設定する
  create: 作成する
  update: 変更する
  delete: 削除する
  passwordStrength: パスワード強度
  passwordScore:
    - 
    - 非常に弱い
    - 弱い
    - 普通
    - 強い
    - 非常に強い
  error:
    invalidPassword: パスワードが正しくありません。
    passwordsDoNotMatch: パスワードが一致しません。
  errorTitle: エラー
s3:
  serviceName: S3
  buckets: バケット
  name: 名称
  size: サイズ
  lastModified: 最終更新日時
  createBucket: 新規バケット作成
  deleteBucket: バケット削除
  bucketProperties: バケットのプロパティ
  createFolder: フォルダ作成
  downloadObjects: ダウンロード
  uploadObjects: ファイルのアップロード
  uploadFolder: フォルダーのアップロード
  deleteObjects: 削除
  deleteConfirmation: 削除の確認
  deleteObjMsg1: "%s を削除しますか？"
  deleteObjMsg2: "%d 個のオブジェクトを削除しますか？"
  deleteBktMsg: バケット %s を削除しますか？
  folderName: フォルダ名
  region: リージョン
  noObject: オブジェクトがありません。
  showVersions: バージョン表示
  deleteMarker: 削除マーカー
  bucketName: バケット名
  create: 作成
  delete: 削除
  startUpload: アップロード開始
  uploadTo: アップロード先
  storageClass: ストレージ クラス
  storageClassName: 
    STANDARD: 標準
    REDUCED_REDUNDANCY: 低冗長化
    STANDARD_IA: 標準 - 低頻度アクセス
  changeBucketAcl: バケットのアクセス許可
  aclGrantee: 対象
  aclRead: 一覧/参照
  aclWrite: アップロード/削除
  aclReadAcp: アクセス権参照
  aclWriteAcp: アクセス権編集
  addGrantee: アクセス許可を追加
  grantee:
    OWNER: 所有者
    ALL_USERS: 全員
    AUTHENTICATED_USERS: 認証済みユーザー
    LOG_DELIVERY: ログ配信
  changeBucketVersioning: バケットのバージョン管理
  versioning: バージョン管理
  versioningDisabled: 無効
  versioningEnabled: 有効
  versioningSuspended: 停止
  changeVersioningMsg: 有効にしたバージョニングを無効にすることはできません。停止のみ可能です。
  regionName:
    us-east-1: US 東海岸（北バージニア）
    us-west-1: US 西海岸（北カルフォルニア）
    us-west-2: US 西海岸（オレゴン）
    eu-west-1: EU （アイルランド）
    eu-central-1: EU （フランクフルト）
    ap-southeast-1: アジアパシフィック（シンガポール）
    ap-southeast-2: アジアパシフィック（シドニー）
    ap-northeast-1: アジアパシフィック（東京）
    ap-northeast-2: アジアパシフィック（ソウル）
    sa-east-1: 南アメリカ（サンパウロ）
  error:
    InvalidAccessKeyId: アクセスキーIDが正しくありません。
    SignatureDoesNotMatch: シークレットアクセスキーが正しくありません。
    BucketAlreadyExists: このバケット名は既に存在します。
    InvalidBucketName: このバケット名は利用できません。
    TooManyBuckets: 許可されているバケット数を超えています。
    BucketNotEmpty: このバケットは空ではありません。
    NoSuchBucket: 指定したバケットは存在しません。
    ServiceUnavailable: サービスが利用できません。
    InternalError: サーバー内部エラー
    AccessDenied: アクセスできません。
ec2:
  serviceName: EC2
  regionName:
    all: 全てのリージョン
    us-east-1: US 東海岸（北バージニア）
    us-west-2: US 西海岸（オレゴン）
    us-west-1: US 西海岸（北カルフォルニア）
    eu-west-1: EU （アイルランド）
    eu-central-1: EU （フランクフルト）
    ap-southeast-1: アジアパシフィック（シンガポール）
    ap-southeast-2: アジアパシフィック（シドニー）
    ap-northeast-1: アジアパシフィック（東京）
    ap-northeast-2: アジアパシフィック（ソウル）
    sa-east-1: 南アメリカ（サンパウロ）
  instance: インスタンス
  start: 開始
  stop: 停止
  reboot: 再起動
  terminate: 削除
  startInstances: インスタンスの開始
  stopInstances: インスタンスの停止
  rebootInstances: インスタンスの再起動
  terminateInstances: インスタンスの削除
  noInstances: インスタンスはありません。
  startInstancesMsg:
   - このインスタンスを開始してよろしいですか？
   - これらのインスタンスを開始してよろしいですか？
  rebootInstancesMsg:
   - このインスタンスを再起動してよろしいですか？
   - これらのインスタンスを再起動してよろしいですか？
  stopInstancesMsg:
   - このインスタンスを停止してよろしいですか？
   - これらのインスタンスを停止してよろしいですか？
  stopInstancesMsg2: |+
   インスタンスを停止すると
   インスタンスのエフェメラルストレージ上のデータは失われます。
  terminateInstancesMsg:
   - このインスタンスを削除してよろしいですか？
   - これらのインスタンスを削除してよろしいですか？
  terminateInstancessMsg2: ""
  runInstances: インスタンスの作成
  manageVpcSubnet: VPC とサブネットの管理
  manageSecurityGroups: セキュリティグループの管理
  createVpc: VPC の作成
  createSubnet: サブネットの作成
  region: リージョン
  availabilityZone: ゾーン
  noPreference: 指定しない
  vpc: VPC
  subnet: サブネット
  cidrBlock: CIDRブロック
  publicIp: パブリック IP
  mapPublicIpOnLaunch: 自動割り当てパブリック IP を有効化
  AMI: AMI
  history: ヒストリ
  quickStart: クイックスタート
  instanceType: インスタンスタイプ
  instanceFamilyDescription:
    generalPurpose: 汎用
    computeOptimized: コンピューティングの最適化
    gpuInstances: GPU インスタンス
    memoryOptimized: メモリ最適化
    storageOptimized: ストレージの最適化
  storage: ストレージ
  deviceName: デバイス
  snapshot: スナップショット
  volumeType: 種別
  sizeGiB: サイズ(GiB)
  ebsVolumeType: EBS種別
  ebsType:
    gp2: 汎用 SSD (GP2)
    io1: プロビジョンド IOPS SSD (IO1)
    standard: マグネティック
  iops: IOPS
  notAvailable: 利用不可
  attributes: 属性
  deleteOnTermination: 合わせて削除
  encrypted: 暗号化
  addNewVolume: 新規ボリューム追加
  nameTag: ネームタグ
  securityGroup: セキュリティグループ
  securityGroups: セキュリティグループ
  inbound: インバウンド
  outbound: アウトバウンド
  ruleType: タイプ
  ruleProtocol: プロトコル
  rulePortRange: ポート範囲 ( / ICMP タイプ-コード)
  ruleSource: 送信元
  ruleDestination: 送信先
  saveChanges: 編集を保存
  discardChanges: 編集を破棄
  addRule: 新しいルールの追加
  noRules:
   inbound: このセキュリティグループにはインバウンドルールがありません
   outbound: このセキュリティグループにはアウトバウンドルールがありません
  all: 全て
  protocol:
    allTraffic: 全てのトラフィック
    allTCP: 全てのTCP
    allUDP: 全てのUDP
    allICMP: 全てのICMP
    customTCP: カスタムTCPルール
    customUDP: カスタムUDPルール
    customICMP: カスタムICMPルール
    dnsUDP: DNS(UDP)
    dnsTCP: DNS(TCP)
    mysql: MYSQL
    mysqlAurora: MYSQL/Aurora
    redshift: Redshift
    postgreSQL: PostgreSQL
    oracleRDS: Oracle-RDS
  icmpProtocol:
    all: All
    echoReply: Echo reply
    destinationUnreachable: Destination unreachable
    destinationNetworkUnreachable: Destination network unreachable
    destinationHostUnreachable: Destination host unreachable
    destinationProtocolUnreachable: Destination protocol unreachable
    destinationPortUnreachable: Destination port unreachable
    fragmentationRequiredAndDfFlagSet: Fragmentation required, and DF flag set
    sourceRouteFailed: Source route failed
    destinationNetworkUnknown: Destination network unknown
    destinationHostUnknown: Destination host unknown
    sourceHostIsolated: Source host isolated
    networkAdministrativelyProhibited: Network administratively prohibited
    hostAdministrativelyProhibited: Host administratively prohibited
    networkUnreachableForTos: Network unreachable for TOS
    hostUnreachableForTos: Host unreachable for TOS
    communicationAdministrativelyProhibited: Communication administratively prohibited
    hostPrecedenceViolation: Host precedence violation
    precedenceCutoffInEffect: Precedence cutoff in effect
    sourceQuench: Sourcei quench
    redirectDatagram: Redirect Datagram
    redirectDatagramForTheNetwork: Redirect Datagram for the network
    redirectDatagramForTheHost: redirect datagram for the host
    redirectDatagramForTheTosAndNetwork: redirect datagram for the TOS & network
    redirectDatagramForTheTosAndHost: redirect datagram for the TOS & host
    alternateHostAddress: Alternate host address
    echoRequest: Echo request
    routerAdvertisement: Router advertisement
    routerSolicitation: Router solicitation
    timeExceeded: Time exceeded
    ttlExpiredTransit: TTL expired transit
    fragmentationReasemblyTimeExceeded: Fragmentation reasembly time exceeded
    parameterProblem: Parameter problem
    pointerIndicatesTheError: Pointer indicates the error
    missingARequiredOption: Missing a required option
    badLength: Bad length
    timestamp: Timestamp
    timestampReply: Timestamp reply
    informationRequest: Information request
    informationReply: Information reply
    addressMaskRequest: Address mask request
    addressMaskReply: Address mask reply
    traceroute: Traceroute
    datagramConversionError: Datagram conversion error
    mobileHostRedirect: Mobile host redirect
    whereAreYou: Where-Are-You
    hereIAm: Here-I-Am
    mobileRegistrationRequest: Mobile registration request
    mobileRegistrationReply: Mobile registration reply
    domainNameRequest: Domain name request
    domainNameReply: Domain name reply
    skipAlgorithmDiscoveryProtocol: SKIP Algorithm Discovery Protocol
    photurisSecurityFailures: Photuris, Security Failures
  createSecurityGroup: セキュリティグループの作成
  securityGroupName: セキュリティグループ名
  securityGroupDescription: 概要
  selectSnapshot: スナップショットの選択
  snapshotId: スナップショットID
  snapshotDescription: 概要
  selectKeyPair: キーペアの選択
  keyName: キーペア名
  keyFingerprint: Fingerprint
  createKeyPair: 新規キーペアの作成
  downloadKeyFile: プライベートキーのダウンロード
  getWindowsPassword: Windowsパスワードの取得
  retrieveWindowsPassword: デフォルトの Windows 管理者パスワードの取得
  passwordNotAvailableYet: パスワードはまだ利用できません。
  retrieveWindowsPasswordMsg: パスワードを取得するためにはこのインスタンスのキーペアが必要です。
  privateKey: プライベートキー
  specifyPrivateKeyPath: ファイルのパスを指定する
  pastPrivateKeyContents: またはプライベートキーの内容をここに貼り付けます
  passwordDecrypted: パスワードの復号に成功しました。
  passwordDecryptionError: パスワードの復号に失敗しました。プライベートキーを確認してください。
  password: パスワード
  error:
    VpcLimitExceeded: VPC の上限数を超えました。
r53:
  serviceName: Route53
  zones: ゾーン
  name: ドメイン名
  ttl: TTL
  type: タイプ
  value: 値
  noHostedZone: ホストされたゾーンはありません。
  createHostedZone: ホストゾーンの作成
  updateHostedZone: ホストゾーンの変更
  deleteHostedZone: ホストゾーンの削除
  deleteHostedZoneMsg: このホストゾーンを削除してよろしいですか？
  createRRSet: レコードセットの作成
  updateRRSet: レコードセットの変更
  deleteRRSet: レコードセットの削除
  deleteRRSetMsg:
   - このレコードセットを削除してよろしいですか？
   - これらのレコードセットを削除してよろしいですか？
  domainName: ドメイン名
  comment: コメント
  hostedZoneType: タイプ
  notPrivateZone: パブリック
  privateZone: プライベート（VPC用）
  associatedVpc: 連携VPC
  rrsetType: タイプ
  ttlBtn:
    "1min": 1分
    "5min": 5分
    "1hour": 1時間
    "1day": 1日
  error:
    AccessDenied: アクセスできません。
    InvalidDomainName: ドメイン名が正しくありません。
    RRSetAlreadyExists: すでに登録されています。
