com:
  setupAwsAccessKey: Setup AWS Access Key
  accessKeyId: Access Key ID
  secretAccessKey: Secret Access Key
  setPassword: Set your password
  setPasswordMsg: Set your password at start up of this application.
  inputPassword: Input password
  updatePassword: Update password
  currentPassword: Current password
  newPassword: New password
  newPassword2: Re-enter new password
  password: Password
  action: Action
  cancel: Cancel
  save: Save
  ok: OK
  set: Set
  create: Create
  update: Update
  delete: Delete
  passwordStrength: Password strength
  passwordScore:
    - 
    - Very weak
    - Weak
    - Good
    - Strong
    - Very strong
  error:
    invalidPassword: Invalid password.
    passwordsDoNotMatch: Passwords do not match.
  errorTitle: Error
s3:
  serviceName: S3
  buckets: Buckets
  name: Name
  size: Size
  lastModified: Last Modified
  createBucket: Create Bucket
  deleteBucket: Delete Bucket
  bucketProperties: Bucket Properties
  createFolder: Create Folder
  downloadObjects: Download
  uploadObjects: Upload Files
  uploadFolder: Upload Folder
  deleteObjects: Delete
  deleteConfirmation: Delete Confirmation
  deleteObjMsg1: Are you sure you want to delete %s?
  deleteObjMsg2: Are you sure you want to delete %d files?
  permanentlyDelete: Permanently delete
  deleteBktMsg: Are you sure you want to delete a bucket %s?
  objectProperties: Object Properties
  changeObjectStorageClass: Change Storage Class
  changeObjectServerSideEncryption: Change ServerSide Encryption
  targetObjects: Target Objects
  selectedObjects: "%d Objects"
  folderName: Folder name
  region: Region
  noObject: No objects found.
  showVersions: Show versions
  deleteMarker: Delete Marker
  bucketName: Bucket Name
  create: Create
  delete: Delete
  startUpload: Start Upload
  uploadTo: Upload to
  storageClass: Storage Class
  storageClassName: 
    STANDARD: Standard
    REDUCED_REDUNDANCY: Reduced Redundancy
    STANDARD_IA: Standard - Infrequent Access
  serverSideEncryption: Server Side Encryption
  serverSideEncryptionNone: None
  serverSideEncryptionAES256: AES256
  changeBucketAcl: Bucket Permisssions
  aclGrantee: Grentee
  aclRead: List/DownLoad
  aclWrite: Upload/Delete
  aclReadAcp: View Permissions
  aclWriteAcp: Edit Permissions
  addGrantee: Add Permissions
  grantee:
    OWNER: Owner
    ALL_USERS: Every one
    AUTHENTICATED_USERS: Any Authenticated AWS User
    LOG_DELIVERY: Log Delivery
  changeBucketVersioning: Bucket Versioning
  versioning: Versioning
  versioningDisabled: Disabled
  versioningEnabled: Enabled
  versioningSuspended: Suspended
  changeVersioningMsg: Once enabled, Versioning cannot be disabled, only suspended.
  changeBucketWebsite: Bucket Static Website Hosting
  websiteHosting: Website Hosting
  websiteEndpoint: Endpoint
  websiteDisabled: Disabled
  websiteEnabled: Enabled
  websiteRedirect: Redirect all to another host
  indexDocument: Index Document
  errorDocument: Error Document
  redirectHost: Redirect Destination Host
  changeObjectMetadata: Modify object metadata
  metadataKey: Key
  metadataValue: Value
  addMetadata: Add metadata
  withoutChange: (without change)
  deleteMetadata: (delete)
  regionName:
    us-east-1: US East (Northern Virginia)
    us-west-1: US West (Northern California)
    us-west-2: US West (Oregon)
    eu-west-1: EU (Ireland)
    eu-central-1: EU (Frankfurt)
    ap-southeast-1: Asia Pacific (Singapore)
    ap-southeast-2: Asia Pacific (Sydney)
    ap-northeast-1: Asia Pacific (Tokyo)
    ap-northeast-2: Asia Pacific (Seoul)
    sa-east-1: South America (Sao Paulo)
  error:
    InvalidAccessKeyId: The AWS access key ID is invalid.
    SignatureDoesNotMatch: The AWS secret access key is invalid.
    BucketAlreadyExists: The requested bucket name is already exist.
    InvalidBucketName: The specified bucket is not valid.
    TooManyBuckets: You have attempted to create more buckets than allowed.
    BucketNotEmpty: The bucket is not empty.
    NoSuchBucket: The specified bucket does not exist.
    ServiceUnavailable: Service Unavailable
    InternalError: Internal Server Error.
    AccessDenied: Access Denied.
ec2:
  serviceName: EC2
  regionName:
    all: All Regions
    us-east-1: US East (Northern Virginia)
    us-west-2: US West (Oregon)
    us-west-1: US West (Northern California)
    eu-west-1: EU (Ireland)
    eu-central-1: EU (Frankfurt)
    ap-southeast-1: Asia Pacific (Singapore)
    ap-southeast-2: Asia Pacific (Sydney)
    ap-northeast-1: Asia Pacific (Tokyo)
    ap-northeast-2: Asia Pacific (Seoul)
    sa-east-1: South America (Sao Paulo)
  instance: Instance
  start: Start
  stop: Stop
  reboot: Reboot
  terminate: Terminate
  instanceState: Instance State
  startInstances: Start Instance
  stopInstances: Stop Instance
  rebootInstances: Reboot Instance
  terminateInstances: Terminate Instance
  instanceSettings: Instance Settings
  changeInstanceType: Change Instance Type
  getSystemLog: Get System Log
  noInstances: No Insatances,
  startInstancesMsg:
   - Are you sure you want to start this instance?
   - Are you sure you want to start these instances?
  rebootInstancesMsg:
   - Are you sure you want to reboot this instance?
   - Are you sure you want to reboot these instances?
  stopInstancesMsg:
   - Are you sure you want to stop this instance?
   - Are you sure you want to stop these instances?
  stopInstancesMsg2: |+
   Note that when your instances are stopped:
   Any data on the ephemeral storage of your instances will be lost.
  terminateInstancesMsg:
   - Are you sure you want to terminate this instance?
   - Are you sure you want to terminate these instances?
  terminateInstancesMsg2: ""
  runInstances: Launch Instance
  manageVpcSubnet: Manage VPC and Subnets
  manageSecurityGroups: Manage Security Groups
  createVpc: Create VPC
  createSubnet: Create Subnet
  region: Region
  availabilityZone: Zone
  noPreference: No preference
  vpc: VPC
  subnet: Subnet
  cidrBlock: CIDR block
  publicIp: Public IP
  mapPublicIpOnLaunch: Enable auto-assign Public IP
  AMI: AMI
  history: History
  quickStart: Quick start
  instanceType: Instance Type
  instanceFamilyDescription:
    generalPurpose: General purpose
    computeOptimized: Compute optimized
    gpuInstances: GPU Instances
    memoryOptimized: Memory optimized
    storageOptimized: Storage optimized
  ebsOptimized: EBS Optimized
  storage: Storage
  deviceName: Device
  snapshot: Snapshot
  volumeType: Type
  sizeGiB: Size(GiB)
  ebsVolumeType: EBS Volume Type
  ebsType:
    gp2: General Purpose SSD (GP2)
    io1: Provisioned IOPS SSD (IO1)
    standard: Magnetic
    st1: Throughput Optimized HDD(ST1)
    sc1: Cold HDD(SC1)
  iops: IOPS
  throughput: Throughput
  notAvailable: N/A
  attributes: Attributes
  deleteOnTermination: Delete On Termination
  encrypted: Encrypted
  addNewVolume: Add New Volume
  nameTag: Name Tag
  securityGroup: Security Group
  securityGroups: Security Groups
  inbound: Inbound
  outbound: Outbound
  ruleType: Type
  ruleProtocol: Protocol
  rulePortRange: Port Range ( / ICMP Type-Code )
  ruleSource: Source
  ruleDestination: Destination
  saveChanges: Save changes
  discardChanges: Discard changes
  addRule: Add new rule
  noRules:
    inbound: This security group has no inbound rules
    outbound: This security group has no outbound rules
  all: All
  protocol:
    allTraffic: All traffic
    allTCP: All TCP
    allUDP: All UDP
    allICMP: All ICMP
    customTCP: Custom TCP Rule
    customUDP: Custom UDP Rule
    customICMP: Custom ICMP Rule
    dnsUDP: DNS(UDP)
    dnsTCP: DNS(TCP)
    mysql: MYSQL
    mysqlAurora: MYSQL/Aurora
    redshift: Redshift
    postgreSQL: PostgreSQL
    oracleRDS: Oracle-RDS
  icmpProtocol:
    all: All
    echoReply: Echo reply
    destinationUnreachable: Destination unreachable
    destinationNetworkUnreachable: Destination network unreachable
    destinationHostUnreachable: Destination host unreachable
    destinationProtocolUnreachable: Destination protocol unreachable
    destinationPortUnreachable: Destination port unreachable
    fragmentationRequiredAndDfFlagSet: Fragmentation required, and DF flag set
    sourceRouteFailed: Source route failed
    destinationNetworkUnknown: Destination network unknown
    destinationHostUnknown: Destination host unknown
    sourceHostIsolated: Source host isolated
    networkAdministrativelyProhibited: Network administratively prohibited
    hostAdministrativelyProhibited: Host administratively prohibited
    networkUnreachableForTos: Network unreachable for TOS
    hostUnreachableForTos: Host unreachable for TOS
    communicationAdministrativelyProhibited: Communication administratively prohibited
    hostPrecedenceViolation: Host precedence violation
    precedenceCutoffInEffect: Precedence cutoff in effect
    sourceQuench: Sourcei quench
    redirectDatagram: Redirect Datagram
    redirectDatagramForTheNetwork: Redirect Datagram for the network
    redirectDatagramForTheHost: redirect datagram for the host
    redirectDatagramForTheTosAndNetwork: redirect datagram for the TOS & network
    redirectDatagramForTheTosAndHost: redirect datagram for the TOS & host
    alternateHostAddress: Alternate host address
    echoRequest: Echo request
    routerAdvertisement: Router advertisement
    routerSolicitation: Router solicitation
    timeExceeded: Time exceeded
    ttlExpiredTransit: TTL expired transit
    fragmentationReasemblyTimeExceeded: Fragmentation reasembly time exceeded
    parameterProblem: Parameter problem
    pointerIndicatesTheError: Pointer indicates the error
    missingARequiredOption: Missing a required option
    badLength: Bad length
    timestamp: Timestamp
    timestampReply: Timestamp reply
    informationRequest: Information request
    informationReply: Information reply
    addressMaskRequest: Address mask request
    addressMaskReply: Address mask reply
    traceroute: Traceroute
    datagramConversionError: Datagram conversion error
    mobileHostRedirect: Mobile host redirect
    whereAreYou: Where-Are-You
    hereIAm: Here-I-Am
    mobileRegistrationRequest: Mobile registration request
    mobileRegistrationReply: Mobile registration reply
    domainNameRequest: Domain name request
    domainNameReply: Domain name reply
    skipAlgorithmDiscoveryProtocol: SKIP Algorithm Discovery Protocol
    photurisSecurityFailures: Photuris, Security Failures
  createSecurityGroup: Create Security Group
  securityGroupName: Security Group Name
  securityGroupDescription: Description
  selectSnapshot: Select Snapshot
  snapshotId: Snapshot ID
  snapshotDescription: Description
  selectKeyPair: Select a key pair
  keyName: Key pair name
  keyFingerprint: Fingerprint
  createKeyPair: Create a new key pair
  downloadKeyFile: Download a private key file
  getWindowsPassword: Get Windows password
  retrieveWindowsPassword: Retrieve Default Windows Administrator Password
  passwordNotAvailableYet: Password not available yet.
  retrieveWindowsPasswordMsg: "In order to retrieve your password you will need your key pair for this instance."
  privateKey: Private key
  specifyPrivateKeyPath: Specify the private key path
  pastPrivateKeyContents: or Paste contents of private key file here.
  passwordDecrypted: The password successfully decrypted.
  passwordDecryptionError: Password Decryption failed. Please ensure your private key.
  password: Password
  error:
    VpcLimitExceeded: The maximum number of VPCs has been reached.
r53:
  serviceName: Route53
  zones: Zones
  name: Domain Name
  ttl: TTL
  type: Type
  value: Value
  noHostedZone: No hosted zone found.
  createHostedZone: Create Hosted Zone
  updateHostedZone: Update Hosted Zone
  deleteHostedZone: Delete Hosted Zone
  deleteHostedZoneMsg: Are you sure you want to delete this Hosted Zone?
  createRRSet: Create Record Set
  updateRRSet: Update Record Set
  deleteRRSet: Delete Record Set
  deleteRRSetMsg:
   - Are you sure you want to delete this Record Set?
   - Are you sure you want to delete these Record Sets?
  domainName: Domain Name
  comment: Comment
  hostedZoneType: Type
  notPrivateZone: Public
  privateZone: Private (for VPC)
  associatedVpc: Associated VPC
  rrsetType: Type
  alias: Alias
  aliasTarget: Alias Target
  aliasTargetGroup:
    s3: -- S3 website endpoints --
    elb: -- ELB load balancers --
    cf: -- CloudFront distributions --
    eb: -- Elastic Beanstalk environments --
    r53: -- Record sets in this hosted zone --
  loadingAliasTarget: loading...
  noAliasTarget: No Targets Available.
  aliasHostedZoneId: Hosted Zone ID
  evaluateTargetHealth: Evaluate Target Health
  yes: Yes
  no: No
  ttlBtn:
    "1min": 1min
    "5min": 5min
    "1hour": 1hour
    "1day": 1day
  error:
    AccessDenied: Access Denied.
    InvalidDomainName: Domain Name is Invalid.
    RRSetAlreadyExists: Record Set is already exists.
