com:
  setupAwsAccessKey: Setup AWS Access Key
  accessKeyId: Access Key ID
  secretAccessKey: Secret Access Key
  setPassword: Set your password
  setPasswordMsg: Set your password at start up of this application.
  inputPassword: Input password
  updatePassword: Update password
  currentPassword: Current password
  newPassword: New password
  newPassword2: Re-enter new password
  password: Password
  action: Action
  cancel: Cancel
  save: Save
  ok: OK
  set: Set
  create: Create
  update: Update
  delete: Delete
  passwordStrength: Password strength
  passwordScore:
    - 
    - Very weak
    - Weak
    - Good
    - Strong
    - Very strong
  error:
    invalidPassword: Invalid password.
    passwordsDoNotMatch: Passwords do not match.
s3:
  serviceName: S3
  buckets: Buckets
  name: Name
  size: Size
  lastModified: Last Modified
  createBucket: Create Bucket
  deleteBucket: Delete Bucket
  bucketProperties: Bucket Properties
  createFolder: Create Folder
  downloadObjects: Download
  uploadObjects: Upload Files
  uploadFolder: Upload Folder
  deleteObjects: Delete
  deleteConfirmation: Delete Confirmation
  deleteObjMsg1: Are you sure you want to delete %s?
  deleteObjMsg2: Are you sure you want to delete %d files?
  deleteBktMsg: Are you sure you want to delete a bucket %s?
  folderName: Folder name
  region: Region
  noObject: No objects found.
  bucketName: Bucket Name
  create: Create
  delete: Delete
  startUpload: Start Upload
  uploadTo: Upload to
  storageClass: Storage Class
  storageClassName: 
    STANDARD: Standard
    REDUCED_REDUNDANCY: Reduced Redundancy
    STANDARD_IA: Standard - Infrequent Access
  regionName:
    us-east-1: US East (Northern Virginia)
    us-west-1: US West (Northern California)
    us-west-2: US West (Oregon)
    eu-west-1: EU (Ireland)
    eu-central-1: EU (Frankfurt)
    ap-southeast-1: Asia Pacific (Singapore)
    ap-southeast-2: Asia Pacific (Sydney)
    ap-northeast-1: Asia Pacific (Tokyo)
    ap-northeast-2: Asia Pacific (Seoul)
    sa-east-1: South America (Sao Paulo)
  error:
    InvalidAccessKeyId: The AWS access key ID is invalid.
    SignatureDoesNotMatch: The AWS secret access key is invalid.
    BucketAlreadyExists: The requested bucket name is already exist.
    InvalidBucketName: The specified bucket is not valid.
    TooManyBuckets: You have attempted to create more buckets than allowed.
    BucketNotEmpty: The bucket is not empty.
    NoSuchBucket: The specified bucket does not exist.
    ServiceUnavailable: Service Unavailable
    InternalError: Internal Server Error.
    AccessDenied: Access Denied.
ec2:
  serviceName: EC2
  regionName:
    all: All Regions
    us-east-1: US East (Northern Virginia)
    us-west-2: US West (Oregon)
    us-west-1: US West (Northern California)
    eu-west-1: EU (Ireland)
    eu-central-1: EU (Frankfurt)
    ap-southeast-1: Asia Pacific (Singapore)
    ap-southeast-2: Asia Pacific (Sydney)
    ap-northeast-1: Asia Pacific (Tokyo)
    ap-northeast-2: Asia Pacific (Seoul)
    sa-east-1: South America (Sao Paulo)
  instance: Instance
  start: Start
  stop: Stop
  reboot: Reboot
  terminate: Terminate
  startInstances: Start Instance
  stopInstances: Stop Instance
  rebootInstances: Reboot Instance
  terminateInstances: Terminate Instance
  noInstances: No Insatances,
  startInstancesMsg:
   - Are you sure you want to start this instance?
   - Are you sure you want to start these instances?
  rebootInstancesMsg:
   - Are you sure you want to reboot this instance?
   - Are you sure you want to reboot these instances?
  stopInstancesMsg:
   - Are you sure you want to stop this instance?
   - Are you sure you want to stop these instances?
  stopInstancesMsg2: |+
   Note that when your instances are stopped:
   Any data on the ephemeral storage of your instances will be lost.
  terminateInstancesMsg:
   - Are you sure you want to terminate this instance?
   - Are you sure you want to terminate these instances?
  terminateInstancesMsg2: ""
  runInstances: Launch Instance
  manageVpcSubnet: Manage VPC and Subnets
  manageSecurityGroups: Manage Security Groups
  createVpc: Create VPC
  createSubnet: Create Subnet
  region: Region
  availabilityZone: Zone
  noPreference: No preference
  vpc: VPC
  subnet: Subnet
  cidrBlock: CIDR block
  publicIp: Public IP
  mapPublicIpOnLaunch: Enable auto-assign Public IP
  AMI: AMI
  instanceType: Instance Type
  instanceFamilyDescription:
    generalPurpose: General purpose
    computeOptimized: Compute optimized
    gpuInstances: GPU Instances
    memoryOptimized: Memory optimized
    storageOptimized: Storage optimized
  storage: Storage
  deviceName: Device
  snapshot: Snapshot
  volumeType: Type
  sizeGiB: Size(GiB)
  ebsVolumeType: EBS Volume Type
  ebsType:
    gp2: General Purpose SSD (GP2)
    io1: Provisioned IOPS SSD (IO1)
    standard: Magnetic
  iops: IOPS
  notAvailable: N/A
  attributes: Attributes
  deleteOnTermination: Delete On Termination
  encrypted: Encrypted
  addNewVolume: Add New Volume
  nameTag: Name Tag
  securityGroup: Security Group
  securityGroups: Security Groups
  inbound: Inbound
  outbound: Outbound
  ruleType: Type
  ruleProtocol: Protocol
  rulePortRange: Port Range
  ruleSource: Source
  ruleDestination: Destination
  all: All
  allTraffic: All traffic
  allTCP: All TCP
  allUDP: All UDP
  allICMP: All ICMP
  customTCP: Custom TCP Rule
  customUDP: Custom UDP Rule
  customICMP: Custom ICMP Rule
  noRules:
   inbound: This security group has no inbound rules
   outbound: This security group has no outbound rules
  createSecurityGroup: Create Security Group
  securityGroupName: Security Group Name
  securityGroupDescription: Description
  selectSnapshot: Select Snapshot
  snapshotId: Snapshot ID
  snapshotDescription: Description
  selectKeyPair: Select a key pair
  keyName: Key pair name
  keyFingerprint: Fingerprint
  createKeyPair: Create a new key pair
  downloadKeyFile: Download a private key file
  retrieveWindowsPassword: Retrieve Default Windows Administrator Password
  passwordNotAvailableYet: Password not available yet.
  retrieveWindowsPasswordMsg: "In order to retrieve your password you will need your key pair for this instance."
  privateKey: Private key
  specifyPrivateKeyPath: Specify the private key path
  pastPrivateKeyContents: or Paste contents of private key file here.
  passwordDecrypted: The password successfully decrypted.
  passwordDecryptionError: Password Decryption failed. Please ensure your private key.
  password: Password
  error:
    VpcLimitExceeded: The maximum number of VPCs has been reached.
r53:
  serviceName: Route53
  zones: Zones
  name: Domain Name
  ttl: TTL
  type: Type
  value: Value
  noHostedZone: No hosted zone found.
  createHostedZone: Create Hosted Zone
  updateHostedZone: Update Hosted Zone
  deleteHostedZone: Delete Hosted Zone
  deleteHostedZoneMsg: Are you sure you want to delete this Hosted Zone?
  createRRSet: Create Record Set
  updateRRSet: Update Record Set
  deleteRRSet: Delete Record Set
  deleteRRSetMsg:
   - Are you sure you want to delete this Record Set?
   - Are you sure you want to delete these Record Sets?
  domainName: Domain Name
  comment: Comment
  hostedZoneType: Type
  notPrivateZone: Public
  privateZone: Private (for VPC)
  associatedVpc: Associated VPC
  rrsetType: Type
  ttlBtn:
    "1min": 1min
    "5min": 5min
    "1hour": 1hour
    "1day": 1day
  error:
    AccessDenied: Access Denied.
    InvalidDomainName: Domain Name is Invalid.
    RRSetAlreadyExists: Record Set is already exists.
